// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejyipmejqdzawquoqweo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqeWlwbWVqcWR6YXdxdW9xd2VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzI2NzAsImV4cCI6MjA2MzUwODY3MH0.RblFo9kQMsdxEFSNUolpNC7f9FMCaGEtKwrPvdNc4Po";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);